version: 2.1

commands:
  sayhello:
    description: 'A very simple command for demonstration purposes'
    parameters:
      to: 
        type: string
        default: 'Hello in workflow is : '
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  print_pipeline_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - sayhello

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # - checkout
      - run:
          name: 'make directory for workspace'
          command: mkdir -p workspace
      - run:
          name: 'save hello_world in output file and set it into workspace'
          command: echo "Hello World" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          # Must be relative path from root
          paths:
            - output.txt

  print-hello-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      # - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run: |
          if [[ `cat /tmp/workspace/output.txt` == "Hello World" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi

workflows:
  say-hello-workflow:
    jobs:
      - print_pipeline_id
      - save_hello_world_output:
          requires:
            - print_pipeline_id
      - print-hello-world:
          requires:
            - save_hello_world_output
